Feature
bonus2k/go-diplom-gophkeeper pull request #1
Opened 2024-08-07 19:06 UTC by bonus2k

2024-08-07 20:44 UTC, Bazys requested changes
есть парочка вопросов

2024-08-07 20:44 UTC, Bazys commented on internal/mvc/form_authorization.go
> +		cu.AddItemInfoList(fmt.Sprintf("Welcome back User!"))
зачем здесь это? `fmt.Sprintf`

2024-08-07 20:44 UTC, Bazys commented on internal/mvc/ui_controller.go
> +		SetDoneFunc(func(buttonIndex int, buttonLabel string) {
Параметр функции, названный `buttonIndex`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `buttonIndex` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-08-07 20:44 UTC, Bazys commented on internal/services/note_service/ui_service.go
> +package note_service
пакеты не именыют с подчеркиванием.

2024-08-07 20:44 UTC, Bazys commented on internal/models/view.go
> +func (cn CredentialNote) GetId() uuid.UUID {
```suggestion
func (cn CredentialNote) GetID() uuid.UUID {
```

ну вот так в го принято

2024-08-07 20:44 UTC, Bazys commented on internal/logger/logger.go
> +func LoggerFromContext(ctx context.Context) *Logger {
снаружи `logger.LoggerFromContext` - масло масляное

2024-08-07 20:44 UTC, Bazys commented on internal/services/note_service/ui_service.go
> +	var l []models.Noteable
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
sliceTypes := make([]Type, 0, len(knownSlice))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-08-07 20:44 UTC, Bazys commented on cmd/server/main.go
> +	listen, err := net.Listen("tcp", ":3200")
константный порт?
может все таки в конфиг?

2024-08-07 20:44 UTC, Bazys commented on internal/mvc/form_text_note.go
> +			note.Id, _ = uuid.NewUUID()
ай ай - ошибки не проверяешь!

2024-08-11 20:28 UTC, bonus2k commented on internal/mvc/form_authorization.go
> +		cu.AddItemInfoList(fmt.Sprintf("Welcome back User!"))
Забыл подстановку добавить)

2024-08-11 20:45 UTC, bonus2k commented on internal/mvc/form_text_note.go
> +			note.Id, _ = uuid.NewUUID()
Довольно странная ошибка)

2024-08-18 13:28 UTC, Bazys approved these changes
меня устраивает, рекомендую сходить на "защиту"

2024-08-19 08:59 UTC, merged